server:
  port: 9090

kafka:
  server: http://localhost:9092
  producer:
    topic: from_parser_to_database
    group-id: ${kafka.producer.topic}
  consumer:
    topic: from_main_to_parser
    group-id: ${kafka.consumer.topic}
