server:
  port: 8585

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whowins
    username: root
    password: Kolovrat015
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

kafka:
  server: http://localhost:9092
  consumer:
    topic: from_parser_to_database
    group-id: "${kafka.consumer.topic}"