server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/whowins
    username: root
    password: Kolovrat015
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  application:
    microservice:
      parser:
        name: WHO_WINS_PARSER
        url: http://localhost:9090/parse
      database:
        name: WHO_WINS_DATABASE
        url: http://localhost:8585

kafka:
  server: http://localhost:9092
  producer:
    id: from_main_to_parser